### ISSUE TITLE
Slight responsiveness issue

### ISSUE THREAD

**Issue by wrdana** [nathalie1226/memory_game#3]
![image](https://cloud.githubusercontent.com/assets/6061907/17012420/332c6912-4f20-11e6-9ff4-a3273ff7de2f.png)

**Comment by wrdana** [comment]
I would also space out the heading from the boxes:
![image](https://cloud.githubusercontent.com/assets/6061907/17012441/6adbd8de-4f20-11e6-8ca7-c71e57264c61.png)

**Comment by nathalie1226** [comment]
i spaced the top but am still working on the lest issue

**Comment by nathalie1226** [comment]
i am turning it into something bootsrap responsive but i have something i cannot figure out so will wait sunday to ask you
shabbat shalom :-)
