### ISSUE TITLE
HTML/CSS issues

### ISSUE THREAD

**Issue by wrdana** [nathalie1226/memory_game#4]
- Input without associate title/label
- Remember Font fallbacks?
- Why didn't you use bootstrap for the responsiveness? I'm glad you practiced media queries, but you should get used to using it..

**Comment by nathalie1226** [comment]
should i change my media query or is it ok?
i am using bootsrap for other assignements i just felt here like media query was more appropriate.
i just tried to add a few fon fallbacks in the body and they are loaded before my font even tough i put my font first in order :'(
